### ISSUE TITLE
use org name that corresponds to the user's dockerhub

### ISSUE THREAD

**Issue by bardec** [jenkins-x/draft-packs#19]
Currently, the maven buildpack (not sure of others) are using a hardcoded [org name](https://github.com/jenkins-x/draft-packs/blob/e5687fb1cce2cca2643d7ea33169f9ed026fe4af/packs/maven/Jenkinsfile#L6) instead of using the one that corresponds to the user's dockerhub repo.

We should probably have a variable interpolated into here that reflects that org name.

**Comment by sanketjpatel** [comment]
Confirming I faced the same issue
